# Generated by Django 3.0.8 on 2020-11-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0003_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(default='random', max_length=200),
        ),
    ]
